version: '3'
services:
  web:
    build:
      context: ./vb-front
      dockerfile: Dockerfile
    image:
      aleczheng/vb-front
    ports:
      - '80:80'
    environment:
      - NGINX_BACK_END=backend
    depends_on:
      - "backend"
  backend:
    build:
      context: ./vb-backend
      dockerfile: Dockerfile.dev
    image:
      aleczheng/vb-backend
    depends_on:
      - "database"
  database:
    image: 'mysql:5'
    environment:
      MYSQL_ROOT_PASSWORD: 'h12345'
      MYSQL_DATABASE: 'visit'
    command: ['--default-authentication-plugin=mysql_native_password', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    ports:
      - 3306:3306
